apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ng-demo-2
spec:
  selector:
    matchLabels:
      app: ng-demo-2
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: ng-demo-2
    spec:
      containers:
      - name: ng-demo-2
        image: ng-demo:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
